server:
  port: 1111
  hostname: eurekaServer1

eureka:
  instance:
    hostname: ${server.hostname}
    lease-expiration-duration-in-seconds: 2 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance,默认为90秒
    lease-renewal-interval-in-seconds: 1 #表示eureka client发送心跳给server端的频率,默认30秒
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #是否开启自我保护模式，默认为true。

security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123456